---
functional:
  - создание игры с ботом
  - создание игры с юзером
non-functional:
  - поддержка мобильных версий
  - сайт должен выдерживать 1000 юзеров одновременно
implicit:
  - сайт должен быть безопасным
  - сайт должен быть оптимизирован для удобства работы
